name: web_logbook_mobile
description: Web Logbook Mobile App
publish_to: 'none'
version: 1.3.0

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path:
  sqflite:
  uuid:
  intl:
  flutter_launcher_icons:
  flutter_secure_storage:
  http:
  suntime:
  logger:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "icons/app.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:

  uses-material-design: true

