name: web_logbook_mobile
description: Web Logbook Mobile App
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.0.0-374.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path:
  sqflite:
  uuid:
  intl:
  flutter_launcher_icons:
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "icons/app.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

